/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RfForm {
    }
}
declare global {
    interface HTMLRfFormElement extends Components.RfForm, HTMLStencilElement {
    }
    var HTMLRfFormElement: {
        prototype: HTMLRfFormElement;
        new (): HTMLRfFormElement;
    };
    interface HTMLElementTagNameMap {
        "rf-form": HTMLRfFormElement;
    }
}
declare namespace LocalJSX {
    interface RfForm {
    }
    interface IntrinsicElements {
        "rf-form": RfForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-form": LocalJSX.RfForm & JSXBase.HTMLAttributes<HTMLRfFormElement>;
        }
    }
}
